# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geno_cor_new <- function(YY, GDD, ww, coorr, mm, KK) {
    .Call('_HDGENE_geno_cor_new', PACKAGE = 'HDGENE', YY, GDD, ww, coorr, mm, KK)
}

geno_cor_new2 <- function(YY, GDD, GDDD, ww, coorr, mm, KK) {
    .Call('_HDGENE_geno_cor_new2', PACKAGE = 'HDGENE', YY, GDD, GDDD, ww, coorr, mm, KK)
}

